---
- name: "Nginx installer for RedOS"
  hosts: "all"
  become: yes
  tasks:
    - name: "Install nginx"
      dnf:
        name: "nginx"
        state: latest
        update_cache: true

    - name: "Start nginx"
      service:
        name: nginx
        state: started