---
- hosts: "all"
  name: "Test playbook for educational purposes"
  become: yes
  tasks:
  - name: "Install vim if not installed"
    dnf:
      name: "vim"
      state: "latest"
      update_cache: true

  - name: "Copy some files"
    copy:
      src: /testfile
      dest: /tmp/testfile

  - name: "Some test with variables and file creating"
    vars:
      var1: Variable-1
#      var2: Variable-2
    file:
      state: touch
      path: /tmp/{{ var1 }}
#    file:
#      state: touch
#      path: /tmp/{{ var2 }}

  - name: "Test with loops"
    file:
      state: touch
      path: /tmp/{{ item }}
    loop:
      - testfile1
      - testfile2
      - testfile3

  - name: "Advanced loop testing"
    shell:
      echo {{ item }} >> /tmp/testfile
    loop: [ 1, 2, 5, 15, 52, 15215, 551, 11, 524, 4, 3, 0 ]
    when: item < 100
